### ISSUE TITLE
Please publish on Pypi

### ISSUE THREAD

**Issue by fricpa** [SequentMicrosystems/16relind-rpi#1]
https://pypi.org/project/SM16inpind/ is published there, why not this one?

This would simplify our deployment.

Thank you!

**Comment by alexburcea2877** [comment]
We will do it and let you know.

**Comment by fricpa** [comment]
That's awesome news, thanks a lot!

**Comment by alexburcea2877** [comment]
You can use now  **_pip install SM16relind_** , is not in the readme yet but is working.

**Comment by fricpa** [comment]
Thanks again, tested it, works great!

**Comment by alexburcea2877** [comment]
Any feedback in the product [page](https://sequentmicrosystems.com/products/sixteen-relays-8-layer-stackable-hat-for-raspberry-pi) will be appreciated.
